<?php
/**
 * Plugin Name: XE DAP NINH BINH AI V2.5
 * Description: AI SEO importer module for WooCommerce. Phân tích URL sản phẩm, viết lại SEO bằng OpenAI và tạo sản phẩm nháp.
 * Version: 2.5.0
 * Author: Xe Đạp Ninh Bình
 * Requires at least: 6.0
 * Requires PHP: 7.4
 */
if (!defined('ABSPATH')) exit;
class XDN_AI_V25 {
 const OPT='xdn_v25_options'; const NONCE='xdn_v25_nonce';
 function __construct(){add_action('admin_menu',[$this,'menu']);add_action('wp_ajax_xdn_v25_preview',[$this,'preview']);add_action('wp_ajax_xdn_v25_create',[$this,'create']);}
 private function opt(){return wp_parse_args(get_option(self::OPT,[]),['api_key'=>'','model'=>'gpt-5-mini']);}
 function menu(){add_submenu_page('xdn-ai-importer','AI SEO V2.5','AI SEO V2.5','manage_woocommerce','xdn-ai-v25',[$this,'page']);}
 function page(){if(!current_user_can('manage_woocommerce'))return;$o=$this->opt();if(isset($_POST['save'])){check_admin_referer('xdn_v25_save');update_option(self::OPT,['api_key'=>trim(sanitize_text_field(wp_unslash($_POST['api_key']??''))),'model'=>sanitize_text_field(wp_unslash($_POST['model']??'gpt-5-mini'))]);$o=$this->opt();echo '<div class="notice notice-success"><p>Đã lưu.</p></div>';} ?>
<div class="wrap"><h1>XE DAP NINH BINH – AI SEO V2.5</h1><div style="background:#fff;border:1px solid #ddd;padding:18px;max-width:1050px"><h2>OpenAI</h2><form method="post"><?php wp_nonce_field('xdn_v25_save');?><input type="hidden" name="save" value="1"><p>API Key<br><input type="password" name="api_key" value="<?php echo esc_attr($o['api_key']);?>" class="regular-text" autocomplete="off"></p><p>Model<br><input name="model" value="<?php echo esc_attr($o['model']);?>" class="regular-text"></p><button class="button button-primary">Lưu</button></form></div><div style="background:#fff;border:1px solid #ddd;padding:18px;margin-top:16px;max-width:1050px"><h2>AI Import sản phẩm</h2><p>Nhập URL sản phẩm nguồn. Plugin phân tích tên, giá, nội dung và ảnh; OpenAI viết lại SEO; sau đó tạo sản phẩm WooCommerce ở trạng thái Nháp.</p><input id="xdn25_url" type="url" placeholder="https://thongnhat.com.vn/..." style="width:650px;max-width:100%"><button id="xdn25_preview" class="button button-primary">Phân tích bằng AI</button><div id="xdn25_out" style="margin-top:15px"></div></div></div>
<script>(function(){const a='<?php echo esc_js(admin_url('admin-ajax.php'));?>',n='<?php echo esc_js(wp_create_nonce(self::NONCE));?>',o=document.getElementById('xdn25_out');const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));document.getElementById('xdn25_preview').onclick=async function(){let u=document.getElementById('xdn25_url').value.trim();if(!u)return alert('Nhập URL sản phẩm.');this.disabled=true;o.innerHTML='Đang phân tích...';let f=new FormData();f.append('action','xdn_v25_preview');f.append('nonce',n);f.append('url',u);try{let j=await(await fetch(a,{method:'POST',body:f})).json();if(!j.success)throw Error(j.data?.message||j.data||'Lỗi');let p=j.data.product;o.innerHTML='<h3>Kết quả</h3><p><b>Tên:</b> '+e(p.name)+'</p><p><b>SEO title:</b> '+e(p.seo_title)+'</p><p><b>Meta:</b> '+e(p.meta_description)+'</p><p><b>Giá:</b> '+e(p.price)+'</p><div style="background:#f6f7f7;padding:12px">'+p.description+'</div><p><b>Ảnh:</b> '+(p.images||[]).length+'</p><button class="button button-primary" id="xdn25_create">Tạo sản phẩm nháp</button>';document.getElementById('xdn25_create').onclick=async()=>{let c=new FormData();c.append('action','xdn_v25_create');c.append('nonce',n);c.append('payload',JSON.stringify(p));let r=await(await fetch(a,{method:'POST',body:c})).json();if(!r.success)return alert(r.data?.message||r.data||'Lỗi');o.innerHTML+='<p style="color:green"><b>Đã tạo sản phẩm nháp #'+e(r.data.id)+'</b></p>'}}catch(x){o.innerHTML='<p style="color:#b32d2e">'+e(x.message)+'</p>'}this.disabled=false}})();</script><?php }
 private function html($url){$r=wp_remote_get($url,['timeout'=>25,'redirection'=>5,'headers'=>['User-Agent'=>'Mozilla/5.0 XDN-AI-Importer/2.5']]);if(is_wp_error($r))return $r;if(wp_remote_retrieve_response_code($r)>=400)return new WP_Error('http','Nguồn trả HTTP '.wp_remote_retrieve_response_code($r));return wp_remote_retrieve_body($r);}
 private function abs($u,$base){if(!$u)return '';if(preg_match('#^https?://#i',$u))return $u;if(strpos($u,'//')===0)return 'https:'.$u;$p=wp_parse_url($base);if(!$p)return $u;if($u[0]==='/')return $p['scheme'].'://'.$p['host'].$u;return $p['scheme'].'://'.$p['host'].'/'.ltrim(dirname($p['path']??'/').'/'.$u,'/');}
 private function extract($html,$url){libxml_use_internal_errors(true);$d=new DOMDocument();@$d->loadHTML('<?xml encoding="utf-8"?>'.$html);$x=new DOMXPath($d);$title=trim($x->evaluate('string(//h1[1])'));if(!$title)$title=trim($x->evaluate('string(//title[1])'));$text=mb_substr(trim(preg_replace('/\s+/u',' ',strip_tags($html))),0,12000);$price='';foreach(['//*[contains(@class,"price")][1]','//*[contains(@class,"woocommerce-Price-amount")][1]'] as $q){$price=trim($x->evaluate('string('.$q.')'));if($price)break;}$images=[];foreach($x->query('//img') as $im){$src=$im->getAttribute('src')?:$im->getAttribute('data-src');$src=$this->abs($src,$url);if($src&&preg_match('/\.(jpe?g|png|webp)(\?.*)?$/i',$src)&&!in_array($src,$images,true))$images[]=$src;if(count($images)>=12)break;}return ['source_url'=>$url,'source_name'=>$title,'source_price'=>$price,'source_text'=>$text,'images'=>$images];}
 private function ai($data){$o=$this->opt();if(empty($o['api_key']))return new WP_Error('key','Chưa nhập OpenAI API Key.');$prompt='Bạn là chuyên gia SEO thương mại điện tử Việt Nam. Viết lại dữ liệu sản phẩm thành nội dung mới, không sao chép nguyên văn. Giữ đúng model, màu sắc, giá và thông số có trong nguồn; không bịa. Trả JSON với name, seo_title, meta_description, short_description, description, price. Description là HTML an toàn cho WooCommerce.\nNguồn:\n'.wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$body=['model'=>$o['model'],'input'=>$prompt,'text'=>['format'=>['type'=>'json_object']]];$r=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>60,'headers'=>['Authorization'=>'Bearer '.$o['api_key'],'Content-Type'=>'application/json'],'body'=>wp_json_encode($body)]);if(is_wp_error($r))return $r;$code=wp_remote_retrieve_response_code($r);$raw=wp_remote_retrieve_body($r);if($code>=300)return new WP_Error('openai','OpenAI HTTP '.$code.': '.mb_substr($raw,0,500));$j=json_decode($raw,true);$out=$j['output_text']??'';if(!$out&&!empty($j['output']))foreach($j['output'] as $item)foreach(($item['content']??[]) as $c)if(isset($c['text']))$out.=$c['text'];$p=json_decode(trim($out),true);if(!is_array($p))return new WP_Error('json','AI không trả JSON hợp lệ.');$p['images']=$data['images'];$p['source_url']=$data['source_url'];return $p;}
 function preview(){if(!current_user_can('manage_woocommerce'))wp_send_json_error(['message'=>'Không có quyền.'],403);check_ajax_referer(self::NONCE,'nonce');$url=esc_url_raw(wp_unslash($_POST['url']??''));if(!$url)wp_send_json_error(['message'=>'URL không hợp lệ.']);$h=$this->html($url);if(is_wp_error($h))wp_send_json_error(['message'=>$h->get_error_message()]);$p=$this->ai($this->extract($h,$url));if(is_wp_error($p))wp_send_json_error(['message'=>$p->get_error_message()]);wp_send_json_success(['product'=>$p]);}
 function create(){if(!current_user_can('manage_woocommerce'))wp_send_json_error(['message'=>'Không có quyền.'],403);check_ajax_referer(self::NONCE,'nonce');if(!function_exists('wc_get_product'))wp_send_json_error(['message'=>'WooCommerce chưa được kích hoạt.']);$p=json_decode(wp_unslash($_POST['payload']??''),true);if(!is_array($p)||empty($p['name']))wp_send_json_error(['message'=>'Dữ liệu không hợp lệ.']);$id=wp_insert_post(['post_title'=>sanitize_text_field($p['name']),'post_content'=>wp_kses_post($p['description']??''),'post_excerpt'=>wp_kses_post($p['short_description']??''),'post_status'=>'draft','post_type'=>'product']);if(!$id)wp_send_json_error(['message'=>'Không tạo được sản phẩm.']);$pr=wc_get_product($id);$price=preg_replace('/[^0-9.]/','',(string)($p['price']??''));if($price!=='')$pr->set_regular_price($price);$pr->save();update_post_meta($id,'_xdn_source_url',esc_url_raw($p['source_url']??''));update_post_meta($id,'_xdn_seo_title',sanitize_text_field($p['seo_title']??''));update_post_meta($id,'_xdn_meta_description',sanitize_textarea_field($p['meta_description']??''));require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/image.php';foreach(($p['images']??[]) as $i=>$img){if($i>=6)break;$att=media_sideload_image($img,$id,null,'id');if(!is_wp_error($att)&&$i===0)set_post_thumbnail($id,$att);}wp_send_json_success(['id'=>$id]);}
}
new XDN_AI_V25();
