<?php
if ( ! defined( 'ABSPATH' ) ) exit;
class XDN_AI_Image_Settings {
 public static function init(){add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_post_xdn_ai_save_image_settings',array(__CLASS__,'save'));add_action('added_post_meta',array(__CLASS__,'after_created_meta'),10,4);add_action('updated_post_meta',array(__CLASS__,'after_created_meta'),10,4);add_action('save_post_product',array(__CLASS__,'watermark_product_content'),40,3);self::hydrate();}
 private static function defaults(){return array('auto_images'=>1,'image_source'=>'ai','image_google_fallback_ai'=>1,'image_limit'=>4,'google_image_key'=>'','google_image_cx'=>'','watermark_enabled'=>1,'watermark_articles'=>1,'watermark_products'=>1,'watermark_skip_thumbnails'=>1,'watermark_logo_id'=>0,'watermark_logo_url'=>'','watermark_position'=>'bottom-right','watermark_opacity'=>75,'watermark_scale'=>0.18,'watermark_margin'=>18);}
 private static function image_settings(){return wp_parse_args(get_option('xdn_ai_image_settings',array()),self::defaults());}
 private static function hydrate(){$main=get_option('xdn_ai_settings',array());$img=self::image_settings();$runtime=$img;if(!empty($img['watermark_logo_id'])){$url=wp_get_attachment_url(absint($img['watermark_logo_id']));if($url){$runtime['watermark_logo_id']=0;$runtime['watermark_logo_url']=$url;}}update_option('xdn_ai_settings',array_merge(is_array($main)?$main:array(),$runtime),false);}
 public static function menu(){add_submenu_page('xdn-ai-content','Ảnh & Logo','Ảnh & Logo','manage_options','xdn-ai-images',array(__CLASS__,'page'));}
 public static function page(){$s=self::image_settings();wp_enqueue_media();echo '<div class="wrap"><h1>🖼️ Ảnh tự động & Logo <small style="font-size:13px;font-weight:400">v'.esc_html(XDN_AI_VERSION).'</small></h1><p>XDN tự chèn ảnh vào vị trí minh họa trong bài. Có thể lấy ảnh từ Google Images hoặc tạo ảnh bằng OpenAI. Thumbnail/ảnh đại diện được bỏ watermark theo mặc định.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('xdn_ai_image_settings');echo '<input type="hidden" name="action" value="xdn_ai_save_image_settings"><table class="form-table">';
 echo '<tr><th>Tự động thêm ảnh vào bài</th><td><label><input type="checkbox" name="auto_images" value="1" '.checked($s['auto_images'],1,false).'> Bật</label><p class="description">AI đánh dấu nơi cần minh họa; nếu AI không đánh dấu, XDN tự lấy một số H2/H3 làm điểm minh họa dự phòng.</p></td></tr>';
 echo '<tr><th>Nguồn ảnh</th><td><select name="image_source"><option value="ai" '.selected($s['image_source'],'ai',false).'>🤖 Tạo bằng OpenAI AI</option><option value="google" '.selected($s['image_source'],'google',false).'>🔎 Google Images</option></select> <label><input type="checkbox" name="image_google_fallback_ai" value="1" '.checked($s['image_google_fallback_ai'],1,false).'> Google lỗi thì tạo AI</label></td></tr>';
 echo '<tr><th>Số ảnh tối đa/bài</th><td><input type="number" min="1" max="8" name="image_limit" value="'.absint($s['image_limit']).'"></td></tr><tr><th>Google Image Search API Key</th><td><input type="password" name="google_image_key" class="regular-text" value="'.esc_attr($s['google_image_key']).'"></td></tr><tr><th>Google Search Engine ID (CX)</th><td><input name="google_image_cx" class="regular-text" value="'.esc_attr($s['google_image_cx']).'"></td></tr>';
 echo '<tr><th>Đóng logo watermark</th><td><label><input type="checkbox" name="watermark_enabled" value="1" '.checked($s['watermark_enabled'],1,false).'> Bật watermark</label><br><label><input type="checkbox" name="watermark_articles" value="1" '.checked($s['watermark_articles'],1,false).'> Ảnh trong bài viết</label><br><label><input type="checkbox" name="watermark_products" value="1" '.checked($s['watermark_products'],1,false).'> Ảnh sản phẩm WooCommerce: gallery + ảnh trong mô tả</label><br><label><input type="checkbox" name="watermark_skip_thumbnails" value="1" '.checked($s['watermark_skip_thumbnails'],1,false).'> <strong>Không đóng logo ảnh Thumbnail/Ảnh đại diện</strong></label></td></tr>';
 echo '<tr><th>Logo</th><td><input type="hidden" id="xdn-logo-id" name="watermark_logo_id" value="'.absint($s['watermark_logo_id']).'"><input id="xdn-logo-url" type="url" name="watermark_logo_url" class="regular-text" value="'.esc_attr($s['watermark_logo_url']).'" placeholder="URL logo PNG/SVG"> <button type="button" class="button" id="xdn-select-logo">Chọn logo từ Media Library</button><div id="xdn-logo-preview" style="margin-top:10px">';if($s['watermark_logo_id'])echo wp_get_attachment_image(absint($s['watermark_logo_id']),array(120,80));echo '</div></td></tr>';
 echo '<tr><th>Vị trí logo</th><td><select name="watermark_position"><option value="bottom-right" '.selected($s['watermark_position'],'bottom-right',false).'>Góc phải dưới</option><option value="bottom-left" '.selected($s['watermark_position'],'bottom-left',false).'>Góc trái dưới</option><option value="top-right" '.selected($s['watermark_position'],'top-right',false).'>Góc phải trên</option><option value="top-left" '.selected($s['watermark_position'],'top-left',false).'>Góc trái trên</option><option value="center" '.selected($s['watermark_position'],'center',false).'>Chính giữa</option></select></td></tr><tr><th>Độ mờ logo</th><td><input type="number" min="10" max="100" name="watermark_opacity" value="'.absint($s['watermark_opacity']).'"> %</td></tr><tr><th>Kích thước logo</th><td><input type="number" min="5" max="50" step="0.01" name="watermark_scale" value="'.esc_attr($s['watermark_scale']).'"> tỷ lệ chiều rộng ảnh</td></tr><tr><th>Khoảng cách mép</th><td><input type="number" min="5" max="100" name="watermark_margin" value="'.absint($s['watermark_margin']).'"> px</td></tr>';
 echo '</table>';submit_button('💾 Lưu cài đặt ảnh & logo');echo '</form><script>jQuery(function($){$("#xdn-select-logo").on("click",function(e){e.preventDefault();const f=wp.media({title:"Chọn logo watermark",button:{text:"Dùng logo này"},multiple:false,library:{type:"image"}});f.on("select",function(){const a=f.state().get("selection").first().toJSON();$("#xdn-logo-id").val(a.id);$("#xdn-logo-url").val(a.url);$("#xdn-logo-preview").html("<img style=\"max-width:120px;max-height:80px\" src=\""+a.url+"\">")});f.open()})});</script></div>';}
 public static function save(){if(!current_user_can('manage_options')||!check_admin_referer('xdn_ai_image_settings'))wp_die('Không có quyền.');$old=self::image_settings();$source=sanitize_key($_POST['image_source']??'ai');$position=sanitize_key($_POST['watermark_position']??'bottom-right');$s=array('auto_images'=>!empty($_POST['auto_images'])?1:0,'image_source'=>in_array($source,array('ai','google'),true)?$source:'ai','image_google_fallback_ai'=>!empty($_POST['image_google_fallback_ai'])?1:0,'image_limit'=>max(1,min(8,absint($_POST['image_limit']??4))),'google_image_key'=>sanitize_text_field($_POST['google_image_key']??$old['google_image_key']),'google_image_cx'=>sanitize_text_field($_POST['google_image_cx']??''),'watermark_enabled'=>!empty($_POST['watermark_enabled'])?1:0,'watermark_articles'=>!empty($_POST['watermark_articles'])?1:0,'watermark_products'=>!empty($_POST['watermark_products'])?1:0,'watermark_skip_thumbnails'=>!empty($_POST['watermark_skip_thumbnails'])?1:0,'watermark_logo_id'=>absint($_POST['watermark_logo_id']??0),'watermark_logo_url'=>esc_url_raw($_POST['watermark_logo_url']??''),'watermark_position'=>in_array($position,array('bottom-right','bottom-left','top-right','top-left','center'),true)?$position:'bottom-right','watermark_opacity'=>max(10,min(100,absint($_POST['watermark_opacity']??75))),'watermark_scale'=>max(0.05,min(0.5,(float)($_POST['watermark_scale']??0.18))),'watermark_margin'=>max(5,min(100,absint($_POST['watermark_margin']??18))));update_option('xdn_ai_image_settings',$s,false);self::hydrate();wp_safe_redirect(add_query_arg(array('page'=>'xdn-ai-images','updated'=>'1'),admin_url('admin.php')));exit;}
 public static function after_created_meta($meta_id,$post_id,$meta_key,$meta_value){if('_xdn_ai_created'!==$meta_key||'1'!=$meta_value||get_post_meta($post_id,'_xdn_ai_images_processed',true))return;$post=get_post($post_id);if(!$post||'post'!==$post->post_type)return;$s=self::image_settings();if(empty($s['auto_images']))return;$content=$post->post_content;if(!preg_match('/<!--\s*XDN_IMAGE\s*:/i',$content)){$count=0;$limit=min(3,absint($s['image_limit']));$content=preg_replace_callback('/(<h[23][^>]*>)(.*?)(<\/h[23]>)/is',function($m)use(&$count,$limit){if($count>=$limit)return$m[0];$heading=trim(wp_strip_all_tags($m[2]));if(!$heading)return$m[0];$count++;return'<!-- XDN_IMAGE: Minh họa cho phần '.$heading.' -->'.$m[0];},$content);} $new=XDN_AI_Images::prepare_article($post_id,$content,$post->post_title);$final=is_string($new)?$new:$post->post_content;if($final!==$post->post_content)wp_update_post(array('ID'=>$post_id,'post_content'=>$final));self::watermark_content_images($final,false);update_post_meta($post_id,'_xdn_ai_images_processed',current_time('mysql'));}
 public static function watermark_product_content($post_id,$post,$update){if(!$post||'product'!==$post->post_type||wp_is_post_revision($post_id)||wp_is_post_autosave($post_id))return;$s=self::image_settings();if(empty($s['watermark_enabled'])||empty($s['watermark_products']))return;self::watermark_content_images($post->post_content,true);}
 private static function watermark_content_images($content,$is_product=false){if(!is_string($content)||!preg_match_all('/<img[^>]+src=[\"\']([^\"\']+)[\"\']/i',$content,$m))return;foreach($m[1] as $url){$id=attachment_url_to_postid(html_entity_decode($url));if($id)XDN_AI_Images::watermark_attachment($id,$is_product);}}
}
