from pathlib import Path
import re

p = Path('xe-dap-ninh-binh/xe-dap-ninh-binh.php')
s = p.read_text(encoding='utf-8')

# Version
s = s.replace('Version: 2.5.2', 'Version: 2.5.3', 1)
s = s.replace("const VERSION = '2.5.2';", "const VERSION = '2.5.3';", 1)
s = s.replace('>V2.5.2</span>', '>V2.5.3</span>', 1)
s = s.replace('V2.5.2: tách tên, giá, ảnh và tự nhận diện sản phẩm biến thể; hỗ trợ thuộc tính, variation và nhiều kiểu phân trang; tối đa 300 sản phẩm mỗi lượt.', 'V2.5.3: cập nhật từ nguồn, chống trùng và hiển thị rõ trạng thái nhập; hỗ trợ thuộc tính, variation, giá và ảnh.', 1)

# AJAX hook
needle = "add_action('wp_ajax_xdn_import_products', [$this, 'ajax_import_products']);"
if "wp_ajax_xdn_update_source" not in s:
    s = s.replace(needle, needle + "\n        add_action('wp_ajax_xdn_update_source', [$this, 'ajax_update_source']);", 1)

# CSS: add compact status/action styles
needle = '.xdn-import-counter strong{font-size:22px}'
extra = '.xdn-import-counter strong{font-size:22px}.xdn-summary{display:flex;gap:18px;flex-wrap:wrap;font-size:15px}.xdn-summary span{font-weight:700}.xdn-skip{color:#996800}.xdn-action{margin:3px 3px 0 0}.xdn-status-note{display:block;margin-top:4px;color:#666;font-size:12px}'
if '.xdn-summary' not in s:
    s = s.replace(needle, extra, 1)

# Counter markup
s = s.replace('<div id="xdn_import_counter" class="xdn-import-counter" role="status" aria-live="polite">Đã nhập thành công <strong>0</strong> sản phẩm</div>', '<div id="xdn_import_counter" class="xdn-import-counter" role="status" aria-live="polite"><div class="xdn-summary"><span class="xdn-ok">Đã nhập thành công: <strong>0</strong></span><span class="xdn-skip">Đã bỏ qua: <strong>0</strong></span><span class="xdn-error">Lỗi: <strong>0</strong></span></div></div>', 1)

# Replace the existing import JS function with V2.5.3 version.
start = s.find('async function importSelected(){')
end = s.find('}})();</script>', start)
if start == -1 or end == -1:
    raise SystemExit('importSelected block not found')
old = s[start:end]
new = r'''async function importSelected(){const items=[...document.querySelectorAll('.item:checked')];if(!items.length)return alert('Chưa chọn sản phẩm.');const fcat=document.getElementById('cat').value||<?php echo (int)$o['default_category'];?>,useAI=document.getElementById('ai').checked?'1':'0',log=document.getElementById('log'),btn=document.getElementById('imp'),counter=document.getElementById('xdn_import_counter');let success=0,skipped=0,failed=0;const total=items.length;const updateCounter=()=>{counter.innerHTML='<div class="xdn-summary"><span class="xdn-ok">Đã nhập thành công: <strong>'+success+'</strong></span><span>Đang xử lý: <strong>'+Math.max(0,total-success-skipped-failed)+'</strong></span><span class="xdn-skip">Đã bỏ qua: <strong>'+skipped+'</strong></span><span class="xdn-error">Lỗi: <strong>'+failed+'</strong></span><span>Tổng chọn: <strong>'+total+'</strong></span></div>';};updateCounter();log.style.display='block';btn.disabled=true;for(const it of items){const p=JSON.parse(it.dataset.json),fd=new FormData(),row=it.closest('tr'),st=row.querySelector('.st');st.textContent='Đang nhập...';fd.append('action','xdn_import_products');fd.append('nonce',nonce);fd.append('products',JSON.stringify([p]));fd.append('category',fcat);fd.append('use_ai',useAI);try{const j=await(await fetch(ajax,{method:'POST',body:fd})).json();if(!j.success)throw Error(j.data||'Lỗi');const x=j.data.results[0];if(x.status==='created'){success++;st.innerHTML='<span class="xdn-ok">Đã tạo #'+x.id+'</span>'}else if(x.status==='exists'){skipped++;st.innerHTML='<span class="xdn-skip">Đã tồn tại #'+x.id+'</span><span class="xdn-status-note">'+esc(x.message||'Sản phẩm đã tồn tại')+'</span> <a class="button button-small xdn-action" target="_blank" href="'+esc(x.edit_url||'#')+'">Xem sản phẩm</a> <button type="button" class="button button-small xdn-action xdn-update-source" data-id="'+esc(x.id)+'" data-url="'+esc(p.url)+'">Cập nhật từ nguồn</button>'}else{skipped++;st.innerHTML='<span class="xdn-skip">Bỏ qua</span><span class="xdn-status-note">'+esc(x.message||'Không nhập')+'</span>'}log.innerHTML+=esc(p.name)+' → '+esc(x.message||'')+'<br>'}catch(e){failed++;st.innerHTML='<span class="xdn-error">Lỗi: '+esc(e.message)+'</span>';log.innerHTML+=esc(p.name)+' → '+esc(e.message)+'<br>'}updateCounter();}btn.disabled=false;updateCounter()}
R.onclick=async function(e){const b=e.target.closest('.xdn-update-source');if(!b)return;const id=b.dataset.id,url=b.dataset.url;if(!id||!url)return;b.disabled=true;b.textContent='Đang cập nhật...';const fd=new FormData();fd.append('action','xdn_update_source');fd.append('nonce',nonce);fd.append('product_id',id);fd.append('source_url',url);fd.append('use_ai',document.getElementById('ai')?.checked?'1':'0');try{const j=await(await fetch(ajax,{method:'POST',body:fd})).json();if(!j.success)throw Error(j.data||'Lỗi');b.outerHTML='<span class="xdn-ok">Đã cập nhật #'+esc(id)+'</span>';if(log){const l=document.getElementById('log');if(l)l.innerHTML+='Cập nhật #'+esc(id)+' → '+esc(j.data?.message||'Đã cập nhật')+'<br>';}}catch(err){b.disabled=false;b.textContent='Cập nhật từ nguồn';alert('Không cập nhật được: '+err.message)}};'''
s = s[:start] + new + s[end:]

# Insert update method immediately before ajax_import_products.
marker = '    public function ajax_import_products(){'
if 'public function ajax_update_source()' not in s:
    method = r'''    private function update_variable_product($post_id,$data,$name,$desc,$short,$ai,$cat){
        $product=wc_get_product($post_id); if(!$product||!($product instanceof WC_Product_Variable)) return new WP_Error('not_variable','Sản phẩm hiện tại không phải sản phẩm có biến thể.');
        $product->set_name($name?:$product->get_name()); $product->set_description($desc); $product->set_short_description($short); if(!empty($data['sku']))$product->set_sku(sanitize_text_field($data['sku'])); $product->save();
        $attrs=[];$attribute_keys=[];foreach((array)($data['attributes']??[]) as $a){$an=sanitize_text_field($a['name']??'');$opts=array_values(array_filter(array_map('sanitize_text_field',(array)($a['options']??[]))));if(!$an||!$opts)continue;$attr=new WC_Product_Attribute();$attr->set_id(0);$attr->set_name($an);$attr->set_options($opts);$attr->set_position(count($attrs));$attr->set_visible(true);$attr->set_variation(true);$attrs[]=$attr;$attribute_keys[$an]=sanitize_title($an);}if($attrs){$product->set_attributes($attrs);$product->save();}
        foreach($product->get_children() as $vid) wp_delete_post($vid,true);
        $created=0;$gallery=[];foreach((array)($data['variations']??[]) as $v){$va=$v['attributes']??[];if(!$va)continue;$variation=new WC_Product_Variation();$variation->set_parent_id($post_id);$variation->set_status('publish');$mapped=[];foreach($va as $label=>$value){$key=$attribute_keys[$label]??sanitize_title($label);$mapped[$key]=sanitize_title($value);}$variation->set_attributes($mapped);$vr=(float)($v['regular_price']??0);$vs=(float)($v['sale_price']??0);if(!$vr&&$vs)$vr=$vs;if($vr>0)$variation->set_regular_price((string)$vr);if($vs>0&&$vs<$vr)$variation->set_sale_price((string)$vs);if(!empty($v['sku']))$variation->set_sku(sanitize_text_field($v['sku']));$vid=$variation->save();$created++;if(!empty($v['image'])){$iid=$this->image_id($v['image'],$post_id);if($iid){$variation->set_image_id($iid);$variation->save();$gallery[]=$iid;}}}
        if(!$created)return new WP_Error('no_variations','Nguồn không còn variation hợp lệ.');foreach(array_slice($data['images']??[],0,12) as $img){$id=$this->image_id($img,$post_id);if($id)$gallery[]=$id;}$gallery=array_values(array_unique($gallery));if($gallery){set_post_thumbnail($post_id,$gallery[0]);if(count($gallery)>1)update_post_meta($post_id,'_product_image_gallery',implode(',',array_slice($gallery,1)));}if($cat)wp_set_object_terms($post_id,[$cat],'product_cat');if(!empty($ai['tags'])&&is_array($ai['tags']))wp_set_object_terms($post_id,array_map('sanitize_text_field',$ai['tags']),'product_tag');if(!empty($ai['seo_title']))update_post_meta($post_id,'_xdn_seo_title',sanitize_text_field($ai['seo_title']));if(!empty($ai['meta_description']))update_post_meta($post_id,'_xdn_meta_description',sanitize_text_field($ai['meta_description']));update_post_meta($post_id,'_xdn_source_data',wp_json_encode($data,JSON_UNESCAPED_UNICODE));update_post_meta($post_id,'_xdn_source_sku',sanitize_text_field($data['sku']??''));update_post_meta($post_id,'_xdn_import_version',self::VERSION);WC_Product_Variable::sync($post_id);wc_delete_product_transients($post_id);return['id'=>$post_id,'variations'=>$created,'images'=>count($gallery)];
    }
    public function ajax_update_source(){
        if(!current_user_can('manage_woocommerce'))wp_send_json_error('Không có quyền.');check_ajax_referer(self::NONCE,'nonce');if(!class_exists('WooCommerce'))wp_send_json_error('WooCommerce chưa được kích hoạt.');$post_id=absint($_POST['product_id']??0);$url=esc_url_raw(wp_unslash($_POST['source_url']??''));if(!$post_id||!$url)wp_send_json_error('Thiếu sản phẩm hoặc URL nguồn.');$data=$this->parse_product($url);if(is_wp_error($data))wp_send_json_error($data->get_error_message());$o=$this->opts();$use_ai=!empty($_POST['use_ai']);$ai=[];if($use_ai){$ai=$this->ai_rewrite($data);if(is_wp_error($ai))wp_send_json_error('OpenAI: '.$ai->get_error_message());}$name=sanitize_text_field($ai['name']??$data['title']??'');$desc=wp_kses_post($ai['description']??$data['content']??'');$short=wp_kses_post($ai['short_description']??$data['short_description']??'');$cat=0;$terms=wp_get_post_terms($post_id,'product_cat',['fields'=>'ids']);if(!is_wp_error($terms)&&!empty($terms))$cat=(int)$terms[0];$product=wc_get_product($post_id);if(!$product)wp_send_json_error('Không tìm thấy sản phẩm WooCommerce.');try{if($product instanceof WC_Product_Variable && !empty($data['variations'])){$r=$this->update_variable_product($post_id,$data,$name,$desc,$short,$ai,$cat);if(is_wp_error($r))wp_send_json_error($r->get_error_message());$msg='Đã cập nhật nguồn: '.$r['variations'].' biến thể, '.$r['images'].' ảnh.';}else{$regular=(float)($data['regular_price']??0);$sale=(float)($data['sale_price']??0);if($sale>0&&$regular>0&&$sale>=$regular)$sale=0;if(!$regular&&$sale)$regular=$sale;$product->set_name($name?:$product->get_name());$product->set_description($desc);$product->set_short_description($short);if($regular>0)$product->set_regular_price((string)$regular);else $product->set_regular_price('');if($sale>0)$product->set_sale_price((string)$sale);else $product->set_sale_price('');if(!empty($data['sku']))$product->set_sku(sanitize_text_field($data['sku']));$product->save();$gallery=[];foreach(array_slice($data['images']??[],0,12) as $img){$id=$this->image_id($img,$post_id);if($id)$gallery[]=$id;}$gallery=array_values(array_unique($gallery));if($gallery){set_post_thumbnail($post_id,$gallery[0]);if(count($gallery)>1)update_post_meta($post_id,'_product_image_gallery',implode(',',array_slice($gallery,1)));}if(!empty($ai['tags'])&&is_array($ai['tags']))wp_set_object_terms($post_id,array_map('sanitize_text_field',$ai['tags']),'product_tag');if(!empty($ai['seo_title']))update_post_meta($post_id,'_xdn_seo_title',sanitize_text_field($ai['seo_title']));if(!empty($ai['meta_description']))update_post_meta($post_id,'_xdn_meta_description',sanitize_text_field($ai['meta_description']));$msg='Đã cập nhật nguồn: '.$gallery_count=count($gallery).' ảnh.';}}
        update_post_meta($post_id,'_xdn_source_url',$url);update_post_meta($post_id,'_xdn_source_data',wp_json_encode($data,JSON_UNESCAPED_UNICODE));update_post_meta($post_id,'_xdn_source_sku',sanitize_text_field($data['sku']??''));update_post_meta($post_id,'_xdn_import_version',self::VERSION);wp_send_json_success(['id'=>$post_id,'message'=>$msg]);
    }

'''
    s=s.replace(marker,method+marker,1)

# Improve exists response with edit URL and explicit reason.
s = s.replace("$results[]=['status'=>'exists','id'=>$existing,'message'=>'Đã tồn tại #'.$existing];", "$results[]=['status'=>'exists','id'=>$existing,'edit_url'=>get_edit_post_link($existing,'',''), 'message'=>'Đã tồn tại sản phẩm WooCommerce #'.$existing.' (trùng URL nguồn).'];", 1)

p.write_text(s,encoding='utf-8')
print('patched', p)
